version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE:-UTC}
      - PLEX_CLAIM=${PLEX_CLAIM:-}
      - ADVERTISE_IP=http://${HOST_IP:-localhost}:32400/
    network_mode: host
    volumes:
      - ${CONFIG_DIR:-/var/lib/nestos/plugins/plex}/config:/config
      - ${TRANSCODE_DIR:-/var/lib/nestos/plugins/plex}/transcode:/transcode
      - ${MEDIA_DIR:-/var/lib/nestos/plugins/plex}/media:/data
    devices:
      - /dev/dri:/dev/dri # Hardware transcoding support (if available)